[package]
name = "git-config-env"
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "Parse git's env configuration"
repository = "https://github.com/crate-ci/git-config-env"
categories = ["command-line-interface", "development-tools", "parsing"]
keywords = ["git", "cli"]
edition = "2018"

[dependencies]
